development:
  adapter: postgresql
  encoding: unicode
  database: slackportal_dev
  host: localhost
  username: alex
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: slackportal_test
  host: localhost
  username: alex
  password: 